### ISSUE TITLE
Accept type defaults to first item

### ISSUE THREAD

**Issue by Javarome** [fastify/fastify-accepts#113]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

2.1.0

### Node.js version

16.13.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.1

### Description

When NO `Accept:` header is specified in the HTTP request,
```
req.accepts().type(a, b)
```
returns `a` by default whereas it should return `null` or `undefined` in such a case. 

### Steps to Reproduce

Issue a query with no `Accept:` header, and ask for a value in a type array. 

### Expected Behavior

return `null`  when no `Accept` header match an array value
return `undefined` when no `Accept` header has been found.

**Comment by mcollina** [comment]
This module has been written with the following idea:

```js
fastify.post('/', function (req, reply) {
  const accept = req.accepts() // Accepts object
  switch(accept.type(['json', 'html'])) {
    case 'json':
      reply.type('application/json').send({hello: 'world'})
      break
    case 'html':
      reply.type('text/html').send('<b>hello, world!</b>')
      break
    default:
      reply.send(Boom.notAcceptable('unacceptable'))
      break
  }
})
```

Your proposed change will make this go into the 'default' block if no Accept header is specified.

I don't see us changing this behaviour as it will further complicate the logic for the end user. However, I'd be happy to review and land a PR that add the behavior you seek behind an option. 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Javarome** [comment]
Let focus on the bug first: is it normal to return the first item of the list when there is no header at all? 
I don't think so because It makes the app assume that a content type has been specified whereas there is not.

For instance in this example the code assume an HTML by default:
```
fastify.post('/', function (req, reply) {
  const accept = req.accepts() // Accepts object
  switch(accept.type(['json', 'html'])) {
    case 'json':
      reply.type('application/json').send({hello: 'world'})
      break
    case 'html':
    default:
      reply.type('text/html').send('<b>hello, world!</b>')
      break
})
```
but where there is not header, it is JSON response that will be returned, not the expected default HTML.

**Comment by mcollina** [comment]
> Let focus on the bug first: is it normal to return the first item of the list when there is no header at all?
I don't think so because It makes the app assume that a content type has been specified whereas there is not.

It is! This issue is not a bug - you would like for this module to work differently than how it is codified atm.
I believe the current behavior provides the best DX.
